#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        1
bspc config normal_border_color   \#000000
bspc config active_border_color   \#ffffff
bspc config window_gap           0 

# height of topbar
bspc config top_padding 20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-scale /home/akad/Documents/wallpapers/wallpaper.jpg
$HOME/.config/polybar/launch.sh
